### ISSUE TITLE
How to Modify the TX and RX pin for SoftwareSerial

### ISSUE THREAD

**Issue by saif1786** [thehapyone/BareBoneSim800#5]
In my project, I was using a TFT LCD screen shield along with sim800 module, hence not able to use digital pin 8 and 9.
Is there any method to modify this by using barebonesim800.h or AltSoftSerial.h?

**Comment by thehapyone** [comment]
You can attempt to change the library to use SoftwareSerial and use any two pins of your choice, but I won't recommend that since it can conflict with other libraries. 

Use this newly modified files, replace the old .h and .c files in the library.
[barebone_temp_fix.zip](https://github.com/thehapyone/BareBoneSim800/files/2771213/barebone_temp_fix.zip)

You can change the Pins used for communication in this section - 
```
 #include "Arduino.h"
 
 #define RX_PIN 10		//not needed since the AltSoftSerial has already define it inside
 #define TX_PIN 11
```
